//
// ColladaSaveOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ColladaSaveOption: SaveOptions {

    /** Gets or sets whether the exported XML document is indented. */
    public var indented: Bool?
    /** Gets or sets  of the Transform Style. */
    public var transformStyle: ColladaTransformStyle?

public enum CodingKeys: String, CodingKey {
        case indented = "Indented"
        case transformStyle = "TransformStyle"
    }

    public init(saveFormat: SaveFormat?, lookupPaths: [String]?, fileName: String?, fileFormat: String?, indented: Bool?, transformStyle: ColladaTransformStyle?) {
        self.indented = indented
        self.transformStyle = transformStyle
        super.init(saveFormat: saveFormat, lookupPaths: lookupPaths, fileName: fileName, fileFormat: fileFormat)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(indented, forKey: "Indented")
        try container.encodeIfPresent(transformStyle, forKey: "TransformStyle")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        indented = try container.decodeIfPresent(Bool.self, forKey: "Indented")
        transformStyle = try container.decodeIfPresent(ColladaTransformStyle.self, forKey: "TransformStyle")
        try super.init(from: decoder)
    }

}

