//
// DracoCompressionLevel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Compression level for draco file */
public enum DracoCompressionLevel: Int32, Codable {
    case NO_COMPRESSION = 0
    case FAST = 1
    case STANDARD = 2
    case OPTIMAL = 3

}
