//
// FileContentType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** File content type */
public enum FileContentType: Int32, Codable {
    case BINARY = 0
    case ASCII = 1

}
