//
// ModelData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Parametric Modeling */

public struct ModelData: Codable {

    /** e.g Node */
    public var type: String?
    public var transform: Transform?
    public var entity: Entity?

public enum CodingKeys: String, CodingKey { 
        case type = "Type"
        case transform = "Transform"
        case entity = "Entity"
    }

    public init(type: String?, transform: Transform?, entity: Entity?) {
        self.type = type
        self.transform = transform
        self.entity = entity
    }


}

