//
// STLSaveOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class STLSaveOption: SaveOptions {

    /** Gets or sets whether flip coordinate system of control points/normal during exporting. */
    public var flipCoordinateSystem: Bool?
    /** Gets or sets  of the FileContent Style. */
    public var fileContentType: FileContentType?

public enum CodingKeys: String, CodingKey {
        case flipCoordinateSystem = "FlipCoordinateSystem"
        case fileContentType = "FileContentType"
    }

    public init(saveFormat: SaveFormat?, lookupPaths: [String]?, fileName: String?, fileFormat: String?, flipCoordinateSystem: Bool?, fileContentType: FileContentType?) {
        self.flipCoordinateSystem = flipCoordinateSystem
        self.fileContentType = fileContentType
        super.init(saveFormat: saveFormat, lookupPaths: lookupPaths, fileName: fileName, fileFormat: fileFormat)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(flipCoordinateSystem, forKey: "FlipCoordinateSystem")
        try container.encodeIfPresent(fileContentType, forKey: "FileContentType")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        flipCoordinateSystem = try container.decodeIfPresent(Bool.self, forKey: "FlipCoordinateSystem")
        fileContentType = try container.decodeIfPresent(FileContentType.self, forKey: "FileContentType")
        try super.init(from: decoder)
    }
    
}

