//
// Transform.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A transform contains information that allow access to object&#39;s translate/scale/rotation or transform matrix at minimum cost This is used by local transform.              */

public struct Transform: Codable {

    /** Gets or sets the translation */
    public var translation: Vector3?
    /** Gets or sets the scale */
    public var scale: Vector3?
    /** Gets or sets the pre-rotation represented in degree */
    public var preRotation: Vector3?
    /** Gets or sets the post-rotation represented in degree */
    public var postRotation: Vector3?
    /** Gets or sets the rotation represented in euler angles, measured in degree              */
    public var eulerAngles: Vector3?

public enum CodingKeys: String, CodingKey { 
        case translation = "Translation"
        case scale = "Scale"
        case preRotation = "PreRotation"
        case postRotation = "PostRotation"
        case eulerAngles = "EulerAngles"
    }

    public init(translation: Vector3?, scale: Vector3?, preRotation: Vector3?, postRotation: Vector3?, eulerAngles: Vector3?) {
        self.translation = translation
        self.scale = scale
        self.preRotation = preRotation
        self.postRotation = postRotation
        self.eulerAngles = eulerAngles
    }


}

