//
// AMFSaveOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class AMFSaveOption: SaveOptions {

    /** Whether to use compression to reduce the final file size, default value is true. */
    public var enableCompression: Bool?

public enum CodingKeys: String, CodingKey {
        case enableCompression = "EnableCompression"
    }

    public init(saveFormat: SaveFormat?, lookupPaths: [String]?, fileName: String?, fileFormat: String?, enableCompression: Bool?) {
        self.enableCompression = enableCompression
        super.init(saveFormat: saveFormat, lookupPaths: lookupPaths, fileName: fileName, fileFormat: fileFormat)
    }

    // Encodable protocol methods
    
    public override func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: String.self)
        
        try container.encodeIfPresent(enableCompression, forKey: "EnableCompression")
        try super.encode(to: encoder)
    }
    
    // Decodable protocol methods
    
    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        
        enableCompression = try container.decodeIfPresent(Bool.self, forKey: "EnableCompression")
        try super.init(from: decoder)
    }

}

