//
// ColladaTransformStyle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The node's transform style of node. */
public enum ColladaTransformStyle: Int32, Codable {
    case COMPONENTS = 0
    case MATRIX = 1

}
