//
// PdfLightingScheme.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Render mode specifies the style in which the 3D artwork is rendered. */
public enum PdfLightingScheme: Int32, Codable {
    case ARTWORK = 0
    case NONE = 1
    case WHITE = 2
    case DAY = 3
    case NIGHT = 4
    case HARD = 5
    case PRIMARY = 6
    case BLUE = 7
    case RED = 8
    case CUBE = 9
    case CAD = 10
    case HEADLAMP = 11

}
