//
// PdfRenderMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Render mode specifies the style in which the 3D artwork is rendered. */
public enum PdfRenderMode: Int32, Codable {
    case SOLID = 0
    case SOLID_WIREFRAME = 1
    case TRANSPARENT = 2
    case TRANSPARENT_WIREFRAME = 3
    case BOUNDING_BOX = 4
    case TRANSPARENT_BOUNDING_BOX = 5
    case TRANSPARENT_BOUNDING_BOX_OUTLINE = 6
    case WIREFRAME = 7
    case SHADED_WIREFRAME = 8
    case HIDDEN_WIREFRAME = 9
    case VERTICES = 10
    case SHADED_VERTICES = 11
    case ILLUSTRATION = 12
    case SOLID_OUTLINE = 13
    case SHADED_ILLUSTRATION = 14

}
