//
// Plane.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Plane Entity */

public struct Plane: Codable {

    /** The name of Plane */
    public var name: String?
    /** Gets or sets the length of the plane.              */
    public var length: Double
    /** Gets or sets the width of the plane              */
    public var width: Double
    /** Gets or sets the length segments.              */
    public var lengthSegments: Int32
    /** Gets or sets the width segments. */
    public var widthSegments: Int32

public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case length = "Length"
        case width = "Width"
        case lengthSegments = "LengthSegments"
        case widthSegments = "WidthSegments"
    }

    public init(name: String?, length: Double, width: Double, lengthSegments: Int32, widthSegments: Int32) {
        self.name = name
        self.length = length
        self.width = width
        self.lengthSegments = lengthSegments
        self.widthSegments = widthSegments
    }


}

