//
// SaveFormat.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** SaveFormat type */
public enum SaveFormat: Int32, Codable {
    case AMF = 0
    case ASE = 1
    case ASPOSE3_D_WEB = 2
    case COLLADA = 3
    case DISCREET3_DS = 4
    case DRACO = 5
    case DXF = 6
    case FBX = 7
    case GLTF = 8
    case HTML = 9
    case JT = 10
    case MICROSOFT3_MF = 11
    case OBJ = 12
    case PDF = 13
    case PLY = 14
    case RVM = 15
    case STL = 16
    case U3_D = 17
    case VRML = 18
    case X = 19

}
