//
// Sphere.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Sphere Entity */

public struct Sphere: Codable {

    /** Gets or sets the Name of Sphere. */
    public var name: String?
    /** Gets or sets the width segments. */
    public var widthSegments: Int32
    /** Gets or sets the height segments.              */
    public var heightSegments: Int32
    /** Gets or sets the phi start.              */
    public var phiStart: Double
    /** Gets or sets the length of the phi. */
    public var phiLength: Double
    /** Gets or sets the theta start.              */
    public var thetaStart: Double
    /** Gets or sets the length of the theta. */
    public var thetaLength: Double
    /** Gets or sets the radius  */
    public var radius: Double

public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case widthSegments = "WidthSegments"
        case heightSegments = "HeightSegments"
        case phiStart = "PhiStart"
        case phiLength = "PhiLength"
        case thetaStart = "ThetaStart"
        case thetaLength = "ThetaLength"
        case radius = "Radius"
    }

    public init(name: String?, widthSegments: Int32, heightSegments: Int32, phiStart: Double, phiLength: Double, thetaStart: Double, thetaLength: Double, radius: Double) {
        self.name = name
        self.widthSegments = widthSegments
        self.heightSegments = heightSegments
        self.phiStart = phiStart
        self.phiLength = phiLength
        self.thetaStart = thetaStart
        self.thetaLength = thetaLength
        self.radius = radius
    }


}

